import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/Components/Shared/Header";
import Footer from "@/Components/Shared/Footer";
import { Varta } from 'next/font/google';
import ReduxProvider from "@/redux/ReduxProvider";

const varta = Varta({
    weight: ['700'],
    subsets: ['latin'],
});

export const metadata = {
  title: "e-Learning",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <body
        suppressHydrationWarning
        className={`${varta?.variable ?? ""} bg-white antialiased`}
      >
        <ReduxProvider>
          
          <Header />
          {children}
          <Footer />
        </ReduxProvider>
      </body>
    </html>
  );
}
